tecla = input('Digite e descubra as caracteríticass de qualquer tecla: ')
n = ('SÃO NÚMEROS?')
l = ('SÃO LETRAS?')
nl = ('SÃO ALFANUMÉRICOS?')
ii = ('SÃO CÓDIGOS ENTRE 0 E 127?')
d = ('SÃO DECIMAIS?')
dg = ('SÃO DÍGITOS?')
i = ('É VÁLIDO EM PYTHON?')
m = ('SÃO MINÚSCULAS?')
p = ('SÃO IMPRIMÍVEIS?')
e = ('SÃO ESPAÇOS EM BRANCO?')
ti = ('SÃO TÍTULOS?')
su = ('SÃO MAIÚSCULAS?')
print('O tipo primitivo desse valor é ', type(tecla))
print(n, tecla.isnumeric())
print(l, tecla.isalpha())
print(nl, tecla.isalnum())
print(ii, tecla.isascii())
print(d, tecla.isdecimal())
print(dg, tecla.isdigit())
print(i, tecla.isidentifier())
print(m, tecla.islower())
print(p, tecla.isprintable())
print(e, tecla.isspace())
print(ti, tecla.istitle())
print(su, tecla.isupper())
